name: Collect Hugging Face Models Count

on:
    workflow_dispatch:
        inputs:
          logLevel:
            description: 'Log level'
            required: false
            default: 'warning'
            type: choice
            options:
            - info
            - warning
            - debug
          tags:
            description: 'Test scenario tags'
            required: false
            type: boolean

    schedule:
        # Runs at 00:00 UTC every day
        -   cron: '0 0 * * *'
    push:
        paths:
            - .github/workflows
            - scripts/
        

jobs:
    collect-models:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: '3.9'

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Collect models data
                run: python scripts/collect_hf_models.py

            -   name: Commit and push if there are changes
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: "chore: update models count"
                    commit_options: "--no-verify"
                    branch: main
                    token: ${{ secrets.GH_TOKEN }}
